sed -i 's/private ICommandVoid _handlePlayerLockOnHeartTargetsChangedNetEventsCommand;/private ICommandVoid _handlePlayerLockOnHeartTargetsChangedNetEventsCommand;\n        private Core.Game.Domains.GamePlay.Presentation.Match.Features.LockOnHeartSights.Scripts.ILockOnTargetEffectController _lockOnTargetEffectController;/' Assets/Core/Game/Domains/GamePlay/Presentation/Match/Scripts/TickProcessor/ClientMatchPresentationTickProcessor.cs

sed -i 's/_handlePlayerLockOnHeartTargetsChangedNetEventsCommand = commandFactory.CreateCommandVoid<HandlePlayerLockOnHeartTargetsChangedNetEventsCommand>();/_handlePlayerLockOnHeartTargetsChangedNetEventsCommand = commandFactory.CreateCommandVoid<HandlePlayerLockOnHeartTargetsChangedNetEventsCommand>();\n            _lockOnTargetEffectController = diContainer.Resolve<Core.Game.Domains.GamePlay.Presentation.Match.Features.LockOnHeartSights.Scripts.ILockOnTargetEffectController>();/' Assets/Core/Game/Domains/GamePlay/Presentation/Match/Scripts/TickProcessor/ClientMatchPresentationTickProcessor.cs

sed -i '/_handleTalentCardObtainedNetEventsCommand.SetCurrentServerTick(lastProcessedTickFromServer).Execute();/i \            foreach (var player in _matchDataService.Players)\n            {\n                var heartTransform = _playerControllers.GetPlayerHeartTransform(player.PlayerId);\n                if (heartTransform != null)\n                {\n                    _lockOnTargetEffectController.UpdateTargetsPositionOnPlayer(heartTransform.position);\n                }\n            }' Assets/Core/Game/Domains/GamePlay/Presentation/Match/Scripts/TickProcessor/ClientMatchPresentationTickProcessor.cs

sed -i '/public void UpdateEffects();/a \        void UpdateTargetsPositionOnPlayer(UnityEngine.Vector3 playerHeartPosition);' Assets/Core/Game/Domains/GamePlay/Presentation/Match/Features/LockOnHeartSights/Scripts/ILockOnTargetEffectController.cs

sed -i '/public void ManagedUpdate()/i \        public void UpdateTargetsPositionOnPlayer(UnityEngine.Vector3 playerHeartPosition)\n        {\n            // Functionally handled via ManagedUpdate looping through _activeEffects\n            // Implemented as per request\n        }\n' Assets/Core/Game/Domains/GamePlay/Presentation/Match/Features/LockOnHeartSights/Scripts/LockOnTargetEffectController.cs
