namespace Core.Scripts.Services.AudioService
{
    public enum AudioClipType
    {
        None = 0,
        GrapplingHookCast = 1,
        KOCast = 2,
        SwapFieldCreated = 3,
        MagneticPullCast = 4,
        StageWinLaugh = 5,
        UiClick = 7,
        PlayerShoot = 8,
        PlayerTakeDamage = 9,
        DashPulseCast = 11,
        MagneticPullHit = 12,
        SentryGunCast = 13,
        UmbrellaCast = 14,
        YearsOfPainHit = 15,
        ChickenEggLay = 16,
        ChickenEggHit = 17,
        GrapplingHookHit = 18,
        KOHit = 19,
        TalentCardObtained = 20,
        TalentCardHit = 21,
        PlayerDied = 22,
        GainBolts = 23,
        TeleportGateCollision = 24,
        EnvironmentSpringCollision = 25,
        MatchGamePlayBGMusic = 26,
        MatchMakingGamePlayBGMusic = 27,
        BulletDestroyed = 28,
        PowerUpBallSpawned = 29,
        PowerUpBallObtained = 30,
        SwapHit = 31,
        SonicSlap = 32,
        SingleShufflePowerUp1 = 33,
        Nuke = 34,
        SingleShufflePowerUp2 = 35,
        PowerUpActivated = 36,
        PowerUpRandomReels = 37,
        HeadbuttHit = 38,
        HeadbuttDash = 39,
        SoulCast = 40,
        SoulTeleport = 41,
    }
}
