namespace CoreDomain.Scripts.Services.AudioService
{
    public enum AudioClipType
    {
        GamePlayBGMusic = 0,
        Stab = 1,
        Jump = 2,
        BalloonPop = 3,
        BubblePop = 4,
        Hit = 5,
        Spin = 6,
        UiClick = 7,
        PlayerShoot = 8,
        PlayerTakeDamage = 9,
        TalentCast = 10,
        DashPulseCast = 11,
        MagneticPullCast = 12,
        SentryGunCast = 13,
        UmbrellaCast = 14,
        YearsOfPainCast = 15,
        ChickenEggLay = 16,
        ChickenEggHit = 17,
        GrapplingHookHit = 18,
        KOHit = 19,
        TalentCardObtained = 20,
        TalentCardHit = 21,
        PlayerDied = 22,
        GainBolts = 23,
        TeleportGateCollision = 24,
        EnvironmentSpringCollision = 25,
        SpinnedStarted = 26,
        SpinnedEnded = 27,
        BulletDestroyed = 28,
        PowerUpBallSpawned = 29,
        PowerUpBallObtained = 30,
        Swap = 31,
    }
}
